/*
	bodyuser.h
	用户界面头文件
	包含所有Body -> user所需的头文件
	主要窗口过程BodyUserOpt1Proc等已包含在mainwnd.h
*/
#include "mainwnd.h"

/*
	USERHOME
*/

//ID
#define USERHOMEID_TREND						0x00001100
#define USERHOMEID_SEARCH						0x00001200
#define USERHOMEID_SEARCH_DESTDEPART			0x00001210
#define USERHOMEID_SEARCH_DEPART				0
#define USERHOMEID_SEARCH_DEST					1
#define USERHOMEID_SEARCH_DESTDEPART_INPUT		0x00001211
#define USERHOMEID_SEARCH_DEPART_INPUT			0
#define USERHOMEID_SEARCH_DEST_INPUT			1
#define USERHOMEID_SEARCH_DATE					0x00001220
#define USERHOMEID_SEARCH_DATE_INPUT			0x00001221
#define USERHOMEID_SEARCH_DATE_INPUT1			0
#define USERHOMEID_SEARCH_DATE_INPUT2			1
#define USERHOMEID_SEARCH_SEARCHBUTTON			0x00001300

//Message
#define WM_U_CANCLESELECTED						WM_USER+300		//用于按钮的取消消息

#define TID_WELCOME								100
#define TID_SELECT								1
#define TID_CANCLESELECT						2
#define TID_HOVER								3
#define TID_CANCLEHOVER							4
/*
	USERBOOKING
*/
#define USERBOOKINGID_SEARCH									0x00002100
#define USERBOOKINGID_SEARCH_SEARCHBAR							0x00002110
#define USERBOOKINGID_SEARCH_SEARCHBAR_CHILD					0x00002110
#define USERBOOKINGID_SEARCH_SEARCHBAR_CHILD_DEPART				0
#define USERBOOKINGID_SEARCH_SEARCHBAR_CHILD_DEST				1
#define USERBOOKINGID_SEARCH_SEARCHBAR_CHILD_DEPARTTIME			2
#define USERBOOKINGID_SEARCH_SEARCHBAR_CHILD_DESTTIME			3

#define USERBOOKINGID_DETAIL									0x00002200
#define USERBOOKINGID_DETAIL_BACKBUTTON							0x00002210
#define USERBOOKINGID_DETAIL_BOOKBUTTON							0x00002220


//Message
//通知Userbooking,展示某个对应航班ID的详细信息，wParam:IDDATA
#define WM_U_SHOWFLIGHTDETAIL					WM_USER+301	
//通知Userbooking,展示搜索结果Search_Ret界面 wParam: TRUE进行检索（从DataFlightIDDATA_Store） FALSE 不进行检索
#define WM_U_SHOWSEARCHUI						WM_USER+302
//通知SearchRet从内存中获取搜索结果数据并展示
#define WM_U_SHOWSEARCHRET						WM_USER+303
//通知UserMine更新用户订单信息(从内存中读取)
#define WM_U_UPDATEORDER						WM_USER+304

/*USER SETTING*/
#define USERSETTINGID_USERINFO										0
#define USERSETTINGID_HELP											1
#define USERSETTINGID_CHILD_BACKBUTTON								0x00003100
#define USERSETTINGID_USERINFO_INPUTNAME							0
#define USERSETTINGID_USERINFO_INPUTIDCARD							1
#define USERSETTINGID_USERINFO_INPUTNICKNAME						2
#define USERSETTINGID_USERINFO_INPUTPASSWORD						3

//Message
